# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: baker
  name: baker
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: baker
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: baker
        actorSystemName: baker
    spec:
      containers:
        - name: baker
          image: baker-http-server:1.0.0-SNAPSHOT
          # Remove for a real project, the image is picked up locally for the integration test
          imagePullPolicy: Never
          # health
          livenessProbe:
            httpGet:
              path: /alive
              port: management
          readinessProbe:
            httpGet:
              path: /ready
              port: management
          #health
          ports:
            # application port
            - name: http
              containerPort: 8080
              protocol: TCP
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            # akka-management bootstrap
            - name: management
              containerPort: 8558
              protocol: TCP

          env:
            - name: APPLICATION_CONF
              value: "kubernetes.conf"
            # The Kubernetes API discovery will use this service name to look for
            # nodes with this value in the 'app' label.
            # This can be customized with the 'pod-label-selector' setting.
            - name: AKKA_CLUSTER_BOOTSTRAP_SERVICE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: "metadata.labels['app']"
#deployment
